// ----------------------------------------------------------------------------
// File: Grid1DBuilder.cpp
// Project: FVGridMaker
// Version: 3.0
// Description:
//   Backend implementation for Grid1DBuilder.
//
//   - Uses 1D distribution functors (Uniform1D, Random1D, ...)
//   - Generates faces and centres on [a, b]
//   - Computes face and cell sizes (dF, dC) in a data-oriented layout
//   - No registry, no std::any; selection by std::type_index.
// License: GNU GPL v3
// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------
// includes FVMGridMaker (ordem alfabética por caminho)
// ----------------------------------------------------------------------------
#include <FVGridMaker/Core/Common/namespace.hpp>
#include <FVGridMaker/Core/Common/types.hpp>
#include <FVGridMaker/ErrorHandling/GridErrors.h>
#include <FVGridMaker/ErrorHandling/Throw.h>

// #include <FVGridMaker/Grid/Grid1D/Grid1D.h>
#include <FVGridMaker/Grid/Grid1D/Builders/Grid1DBuilder.hpp>
#include <FVGridMaker/Grid/Grid1D/Patterns/Distribution/ConceptsDistribution.hpp>
#include <FVGridMaker/Grid/Grid1D/Patterns/Distribution/Random1D.hpp>
#include <FVGridMaker/Grid/Grid1D/Patterns/Distribution/Uniform1D.hpp>

// ----------------------------------------------------------------------------
// includes C++ (alphabetical)
// ----------------------------------------------------------------------------
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <span>
#include <string>
#include <typeindex>
#include <vector>

FVGRIDMAKER_NAMESPACE_OPEN
GRID_NAMESPACE_OPEN
GRID1D_NAMESPACE_OPEN
BUILDERS_NAMESPACE_OPEN
DETAIL_NAMESPACE_OPEN

using core::Index;
using core::Real;

//
using patterns::distribution::Distribution1D;
using patterns::distribution::Random1D;
using patterns::distribution::Uniform1D;

// -----------------------------------------------------------------------------
// Helper: builds a Grid1D for a given distribution functor
// -----------------------------------------------------------------------------

/**
 * @brief Build a Grid1D using a specific 1D distribution functor.
 *
 * This function assumes that Grid1DBuilderConfig provides at least:
 *   - Index n;        // number of physical cells
 *   - Real  a;        // left domain boundary
 *   - Real  b;        // right domain boundary
 *
 * Volumes fictícios (cfg.nGhost) are generated by extending the first and last
 * physical face spacing outside the physical domain. Centering is still
 * reserved for the future policy layer.
 */
template <Distribution1D Dist>
static Grid1D build_with_distribution(const Grid1DBuilderConfig& cfg) {
    // -------------------------------------------------------------------------
    // 1. Extract basic configuration
    // -------------------------------------------------------------------------
    const Index n = cfg.n;
    const Real  a = cfg.a;
    const Real  b = cfg.b;
    const Index n_ficticios = cfg.nGhost;

    if (n <= Index{0}) {
        ::FVGridMaker::error::lancarErro(
            ::FVGridMaker::error::GridErr::InvalidN,
            {{"N", std::to_string(n)}});
    }
    if (!(b > a)) {
        ::FVGridMaker::error::lancarErro(
            ::FVGridMaker::error::GridErr::InvalidDomain,
            {{"A", std::to_string(a)}, {"B", std::to_string(b)}});
    }
    if (n_ficticios < Index{0}) {
        ::FVGridMaker::error::lancarErro(
            ::FVGridMaker::error::GridErr::InvalidFictitiousVolumes,
            {{"N", std::to_string(n_ficticios)}});
    }

    const std::size_t n_physical = static_cast<std::size_t>(n);
    const std::size_t n_fict = static_cast<std::size_t>(n_ficticios);
    const std::size_t n_cells = n_physical + 2u * n_fict;
    const std::size_t n_faces = n_cells + 1u;

    // -------------------------------------------------------------------------
    // 2. Allocate SoA arrays: faces, centres, face sizes, cell "spacings"
    // -------------------------------------------------------------------------
    std::vector<Real> xf(n_faces);       // faces: x_{1/2}, ..., x_{N+1/2}
    std::vector<Real> xc(n_cells);       // centres: x_1, ..., x_N
    std::vector<Real> dF(n_cells);       // Δx_F: face-to-face distances (N)
    std::vector<Real> dC(n_cells + 1u);  // Δx_C: (N+1) entries:
                                         //   [0]     : x_1   - x_{1/2}
                                         //   [1..N-1]: x_i   - x_{i-1}
                                         //   [N]     : x_{N+1/2} - x_N

    // -------------------------------------------------------------------------
    // 3. Run the distribution functor on the physical domain [a, b]
    // -------------------------------------------------------------------------
    Dist dist{};

    std::vector<Real> xf_physical(n_physical + 1u);
    std::span<Real> xf_physical_span{xf_physical.data(), xf_physical.size()};

    using Size = typename Dist::Size;

    // Se Dist::Size for unsigned (size_t), o cast explícito evita warnings
    // de conversão de sinal sem alterar o comportamento.
    dist.makeFaces(static_cast<Size>(n), a, b, xf_physical_span);

    const Real dx_left = xf_physical[1] - xf_physical[0];
    const Real dx_right = xf_physical[n_physical] - xf_physical[n_physical - 1u];

    for (std::size_t k = 0; k < n_fict; ++k) {
        const std::size_t idx = n_fict - 1u - k;
        xf[idx] = a - static_cast<Real>(k + 1u) * dx_left;
    }

    for (std::size_t i = 0; i <= n_physical; ++i) {
        xf[n_fict + i] = xf_physical[i];
    }

    for (std::size_t k = 0; k < n_fict; ++k) {
        xf[n_fict + n_physical + 1u + k] =
            b + static_cast<Real>(k + 1u) * dx_right;
    }

    for (std::size_t i = 0; i < n_cells; ++i) {
        xc[i] = Real(0.5) * (xf[i] + xf[i + 1u]);
    }

    // -------------------------------------------------------------------------
    // 4. Compute face distances dF
    // -------------------------------------------------------------------------
    for (std::size_t i = 0; i < n_cells; ++i) {
        dF[i] = xf[i + 1] - xf[i];
    }

    // -------------------------------------------------------------------------
    // 5. Compute cell "spacings" dC (mesma convenção do código antigo)
    // -------------------------------------------------------------------------
    dC.front() = xc.front() - xf.front();
    if (n_cells >= 2) {
        for (std::size_t i = 1; i < n_cells; ++i) {
            dC[i] = xc[i] - xc[i - 1];
        }
    }
    dC.back() = xf.back() - xc.back();

    // -------------------------------------------------------------------------
    // 6. Build the Grid1D object
    //
    // Mantém a mesma chamada usada anteriormente:
    //   Grid1D{faces, centres, dF, dC}
    // Se a assinatura de Grid1D mudar no futuro (ex.: suportar ghosts
    // explicitamente), basta ajustar esta linha, sem alterar o builder.
    // -------------------------------------------------------------------------
    return Grid1D{std::move(xf), std::move(xc),
                  std::move(dF), std::move(dC),
                  n, n_ficticios, cfg.centering};
}

// -----------------------------------------------------------------------------
// Public backend: dispatch by distribution type
// -----------------------------------------------------------------------------

/**
 * @brief Backend for Grid1DBuilder::build().
 *
 * @param cfg               Aggregated builder configuration.
 * @param distribution_type std::type_index of the selected distribution functor.
 * @param centering_type    std::type_index of centering policy (currently
 *                          unused here; centering is encoded via distributions
 *                          or can be handled by a future policy layer).
 *
 * This function replaces the old registry-based implementation:
 *   - No singletons
 *   - No std::any
 *   - Selection by typeid(Dist) + concepts (Distribution1D)
 */
Grid1D build_grid1d(const Grid1DBuilderConfig& cfg,
                    const std::type_index& distribution_type,
                    const std::type_index& /*centering_type*/) {
    // NOTE:
    // Para adicionar novas distribuições, basta:
    //   1) Incluir o header correspondente;
    //   2) Acrescentar mais um "if" abaixo.
    //
    // Exemplo:
    //   if (distribution_type == typeid(LogStretch1D)) {
    //       return build_with_distribution<LogStretch1D>(cfg);
    //   }

    if (distribution_type == typeid(Uniform1D)) {
        return build_with_distribution<Uniform1D>(cfg);
    }

    if (distribution_type == typeid(Random1D)) {
        return build_with_distribution<Random1D>(cfg);
    }

    ::FVGridMaker::error::lancarErro(
        ::FVGridMaker::error::GridErr::InvalidDistribution,
        {{"dist", distribution_type.name()}});
}

DETAIL_NAMESPACE_CLOSE
BUILDERS_NAMESPACE_CLOSE
GRID1D_NAMESPACE_CLOSE
GRID_NAMESPACE_CLOSE
FVGRIDMAKER_NAMESPACE_CLOSE
