include_guard()

string(TIMESTAMP FVG_BUILD_TIMESTAMP "%Y-%m-%dT%H:%M:%SZ" UTC)
string(TIMESTAMP FVG_BUILD_DATE "%Y-%m-%d" UTC)

set(FVG_PROJECT_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(FVG_PROJECT_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(FVG_PROJECT_VERSION_PATCH "${PROJECT_VERSION_PATCH}")

if(PROJECT_VERSION_TWEAK)
    set(FVG_PROJECT_VERSION_TWEAK "${PROJECT_VERSION_TWEAK}")
else()
    set(FVG_PROJECT_VERSION_TWEAK 0)
endif()

set(FVG_VERSION_SEMANTIC
    "${FVG_PROJECT_VERSION_MAJOR}.${FVG_PROJECT_VERSION_MINOR}.${FVG_PROJECT_VERSION_PATCH}"
)

set(FVG_GIT_AVAILABLE FALSE)
set(FVG_GIT_REPOSITORY FALSE)
set(FVG_GIT_HASH "unknown")
set(FVG_GIT_BRANCH "unknown")
set(FVG_GIT_DIRTY_SUFFIX "")
set(FVG_GIT_EXACT_TAG "")

find_package(Git QUIET)

if(GIT_FOUND)
    set(FVG_GIT_AVAILABLE TRUE)

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --is-inside-work-tree
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        RESULT_VARIABLE FVG_GIT_REPOSITORY_RESULT
        OUTPUT_VARIABLE FVG_GIT_REPOSITORY_OUTPUT
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    if(FVG_GIT_REPOSITORY_RESULT EQUAL 0 AND
       FVG_GIT_REPOSITORY_OUTPUT STREQUAL "true")
        set(FVG_GIT_REPOSITORY TRUE)

        execute_process(
            COMMAND "${GIT_EXECUTABLE}" rev-parse --short=12 HEAD
            WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
            RESULT_VARIABLE FVG_GIT_HASH_RESULT
            OUTPUT_VARIABLE FVG_GIT_HASH_OUTPUT
            ERROR_QUIET
            OUTPUT_STRIP_TRAILING_WHITESPACE
        )

        if(FVG_GIT_HASH_RESULT EQUAL 0 AND NOT FVG_GIT_HASH_OUTPUT STREQUAL "")
            set(FVG_GIT_HASH "${FVG_GIT_HASH_OUTPUT}")
        endif()

        execute_process(
            COMMAND "${GIT_EXECUTABLE}" branch --show-current
            WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
            RESULT_VARIABLE FVG_GIT_BRANCH_RESULT
            OUTPUT_VARIABLE FVG_GIT_BRANCH_OUTPUT
            ERROR_QUIET
            OUTPUT_STRIP_TRAILING_WHITESPACE
        )

        if(FVG_GIT_BRANCH_RESULT EQUAL 0 AND NOT FVG_GIT_BRANCH_OUTPUT STREQUAL "")
            set(FVG_GIT_BRANCH "${FVG_GIT_BRANCH_OUTPUT}")
        else()
            execute_process(
                COMMAND "${GIT_EXECUTABLE}" rev-parse --abbrev-ref HEAD
                WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
                RESULT_VARIABLE FVG_GIT_BRANCH_FALLBACK_RESULT
                OUTPUT_VARIABLE FVG_GIT_BRANCH_FALLBACK_OUTPUT
                ERROR_QUIET
                OUTPUT_STRIP_TRAILING_WHITESPACE
            )

            if(FVG_GIT_BRANCH_FALLBACK_RESULT EQUAL 0 AND
               NOT FVG_GIT_BRANCH_FALLBACK_OUTPUT STREQUAL "")
                set(FVG_GIT_BRANCH "${FVG_GIT_BRANCH_FALLBACK_OUTPUT}")
            endif()
        endif()

        execute_process(
            COMMAND "${GIT_EXECUTABLE}" status --porcelain
            WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
            RESULT_VARIABLE FVG_GIT_STATUS_RESULT
            OUTPUT_VARIABLE FVG_GIT_STATUS_OUTPUT
            ERROR_QUIET
            OUTPUT_STRIP_TRAILING_WHITESPACE
        )

        if(FVG_GIT_STATUS_RESULT EQUAL 0 AND
           NOT FVG_GIT_STATUS_OUTPUT STREQUAL "")
            set(FVG_GIT_DIRTY_SUFFIX "-dirty")
        endif()

        execute_process(
            COMMAND "${GIT_EXECUTABLE}" describe --tags --exact-match HEAD
            WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
            RESULT_VARIABLE FVG_GIT_TAG_RESULT
            OUTPUT_VARIABLE FVG_GIT_TAG_OUTPUT
            ERROR_QUIET
            OUTPUT_STRIP_TRAILING_WHITESPACE
        )

        if(FVG_GIT_TAG_RESULT EQUAL 0 AND NOT FVG_GIT_TAG_OUTPUT STREQUAL "")
            set(FVG_GIT_EXACT_TAG "${FVG_GIT_TAG_OUTPUT}")
        endif()
    endif()
endif()

if(FVG_GIT_REPOSITORY)
    if(FVG_GIT_EXACT_TAG)
        set(FVG_VERSION_FULL "${FVG_VERSION_SEMANTIC}${FVG_GIT_DIRTY_SUFFIX}")
    else()
        set(FVG_VERSION_FULL
            "${FVG_VERSION_SEMANTIC}+${FVG_GIT_HASH}${FVG_GIT_DIRTY_SUFFIX}"
        )
    endif()
else()
    set(FVG_VERSION_FULL "${FVG_VERSION_SEMANTIC}")
endif()

message(STATUS "FVGridMaker version: ${FVG_VERSION_FULL}")
message(STATUS "Git available: ${FVG_GIT_AVAILABLE}")
message(STATUS "Git repository: ${FVG_GIT_REPOSITORY}")
message(STATUS "Git hash: ${FVG_GIT_HASH}")
message(STATUS "Git branch: ${FVG_GIT_BRANCH}")